logger:
  level: info

global:
  max:
    ue: 1024

smf:
  sbi:
    server:
      - address: 0.0.0.0
        port: 80
        advertise: smf
    client:
      nrf:
        - uri: http://nrf
  pfcp:
    server:
      - address: 0.0.0.0
    client:
      upf:
        - address: upf
  gtpc:
    server:
      - address: 0.0.0.0
  gtpu:
    server:
      - address: 0.0.0.0
  metrics:
    server:
      - address: 0.0.0.0
        port: 9090
  session:
    - subnet: 10.45.0.0/16
      gateway: 10.45.0.1
    - subnet: 2001:db8:cafe::/48
      gateway: 2001:db8:cafe::1
  dns:
    - 8.8.8.8
    - 8.8.4.4
  mtu: 1400

time:
  nf_instance:
    validity: 86400
    heartbeat: 60
